name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build app image
        run: docker compose build --no-cache

      - name: Install deps (composer service)
        run: docker compose run --rm composer install --prefer-dist --no-interaction

      - name: Start httpbin
        run: docker compose up -d httpbin

      - name: Run tests with coverage
        run: docker compose run --rm app ./vendor/bin/phpunit --colors=always --coverage-clover=build/logs/clover.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ env.CODECOV_TOKEN }}
          files: build/logs/clover.xml
          flags: unittests
          fail_ci_if_error: true
