name: CI
on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build app image
        run: docker compose build --no-cache
      - name: Install deps (composer service)
        run: docker compose run --rm composer install --prefer-dist --no-interaction
      - name: Start httpbin
        run: docker compose up -d httpbin
      - name: Run tests
        run: docker compose run --rm app ./vendor/bin/phpunit --colors=always --coverage-clover coverage.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: true
